### PR TITLE
Upgrade cached dependencies and fix load classes

### PR DESCRIPTION
**Pull request by peter279k**
Fixes #

## Proposed Changes

  - It seems that the minimum PHP version is `php-7.2` on GitHub action.
It should let this package require `php-7.2` version at least and upgrade cached dependencies (`composer.lock`) with `php-7.2` version.
  - To fix `Deprecation Notice: Class RKD\Banklink\Test\ECommerce\ECommerceTes` message during `composer install` command, it should fix the namespace.
  - To fix `Deprecation Notice: Class RKD\Banklink\Test\Protocol\LiisiPaymentTest` message during `composer install` command, it should let the PHP file name be same as the class name.

### CODE REVIEW

**Comment by peter279k** [comment]
It seems that the `php-7.2` test is failed on GitHub action when executing the ` PHP Mess Detector`.

The error messages are as follows:

```
/home/runner/work/Banklink/Banklink/src/Protocol/ECommerce.php:251	Avoid using undefined variables such as '$signature' which will lead to PHP notices.
/home/runner/work/Banklink/Banklink/src/Protocol/ECommerce.php:254	Avoid using undefined variables such as '$signature' which will lead to PHP notices.
/home/runner/work/Banklink/Banklink/src/Protocol/IPizza.php:444	Avoid using undefined variables such as '$signature' which will lead to PHP notices.
/home/runner/work/Banklink/Banklink/src/Protocol/IPizza.php:447	Avoid using undefined variables such as '$signature' which will lead to PHP notices.
```

These should be fixed because of undefined variables.

I think it's out of range for this PR and I think it can be the next PR to resolve this :).

**Comment by renekorss** [comment]
Hi!

Thanks for PR. Unfortunately I can't require PHP 7.2 yet because some packages are still running on 7.1 which require this package.
Even I'm only testing on >= 7.2, it still needs to be installable on 7.1 for some time.

Could you remove composer edits and make PR against `3.x-dev` branch?

**Comment by peter279k** [comment]
> Hi!
> 
> Thanks for PR. Unfortunately I can't require PHP 7.2 yet because some packages are still running on 7.1 which require this package.
> Even I'm only testing on >= 7.2, it still needs to be installable on 7.1 for some time.
> 
> Could you remove composer edits and make PR against `3.x-dev` branch?

@renekorss, thanks for your reply :).

I think we can go back to require PHP `7.1` version at least.

**Comment by peter279k** [comment]
Hi @renekorss, I've removed composer edits and let this package go back to require `php-7.0` version at least.

And adding the `branch-alias` setting on `composer.json` file.

If having any suggestion, please feel free to write comments on this PR :).

Thanks.

**Pull request merged**
